appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c34442d3aeb3c070045b3b5
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: Z5fs+gNHRhK0CRRtXoRz1f04n1tJoq6I7q9GlK3w8N5GiWk1rm861xrxveJxyosHS1wdjb9ef6b5XB4rBlhF5Xrzljk3NVvukT6z5ZUkxmffewnH7tJ8pCC2wfq3dZFKCdiO08I1OtQNG8aTMU+2gX5jgiHK/5BUArFq+Jcz8ms6B3Pbs5TdJfnXLqigbxt6WHKk/5KZDHcDQzR8PjiiBDoK5O0z/2T6nkvkzzHKPFZWKJzogC83v4rRTwwkBMz9Vb21AEi7uau8Ck8XsgkNIqX7HiQ8yzCz0a+KgAAp3QYfNJ3oZ2w+3+jRscdW3ELoUjB0TOkg0nypU1hrvVRL62b10mka0mWdKd+WddDZ21BLfLcbhbH4QdHWWBxnruXv95ECgoeVMHOtmKquAOFghiUZopxd8zLYruAGa4b/J+KHocIxv4Dmm6/HIVCGDSgsLZgM1W9ZNG51opeywldncCtsjaOASI/H0iVmgprvSOGZzIHkLAybAL51mrJszSGgh2krYBNBgk6Un7QqOOXPIQDzDyyRrHs6k/KctRfXhQDEFLyu4l9z3kT0dSvtR+kwYoPE3/ycUNDM2UBqbqllhda5+zqGjXZIqz/r7O5B4uVisekeTXBg4LcFUkT9qszGMVmgi6QMvqUAvJrlVH2VjnN86Zco1IjwtNIBG0h4TtM=}
